version: '3.8'

services:
  ground_station:
    image: gnuradio_lora
    container_name: gnuradio_lora
    build:
      context: ./
      dockerfile: Dockerfile
    devices:
      - /dev/bus/usb:/dev/bus/usb